### ISSUE TITLE
Cookiecutter Version to Readme

### ISSUE THREAD

**Issue by gtdang** [AutoResearch/autora-template-cookiecutter#20]
Marina had trouble with the cookiecutter template because Cookiecutter installed with anaconda defaulted to an older version (1.7.x). The solution was to install the latest version 2.1.1. 

We should add to the readme to make sure the cookiecutter version is >= 2.1.1 (version we developed with). 
Or alternatively suggest, if you are facing issues make sure you are running the latest version of cookiecutter.

**Comment by younesStrittmatter** [comment]
Yes. That's a good idea. Let's put it into the Readme (I think we should write >= 2.1.1)

**Comment by benwandrew** [comment]
this seems pretty trivial so i just [committed](https://github.com/AutoResearch/autora-template-cookiecutter/commit/a624ae646c187284663ecf615ba6fee1571ac5e1) something to the main branch. apologies if branching with a PR was still better practice... 

does this work?

**Comment by gtdang** [comment]
Perfect! Thank you!
