### ISSUE TITLE
Add way to create everything for full template repo 

### ISSUE THREAD

**Issue by gtdang** [AutoResearch/autora-template-cookiecutter#5]
Considerations: 
* Need to change the readme to have everything

**Comment by gtdang** [comment]
@younesStrittmatter 
I've been thinking about how to best implement this one... Do we want to have a "generate all" baked into the cookiecutter template? Or should we just write a separate function that handles this? 

Option 1: Creating an external function 
- This function would call the cookiecutter for all permutations similarly to how we do it in the tests (in a temp directory). It would copy and merge all the src directories together in a new directory. 
- Edit the text files to remove all if/else jinja constructs so we have all the conditional sections. 
- Run a replacement to replace jinja variables with preferred defaults. 

Option 2 Adding an "All" option to the Autora Contribution Types 
- Change logic in cookiecutter.json to default parameters if All is chosen 
- Post-hook would run a function similar to Option 1 for the src folder creation and merging. 
- Update readme logic to not remove sections if "All" is the contribution type 
- Would adding this option be confusing to users? I am guessing this feature will mostly be used internally to create the non-cookiecutter template repo. 

What are your thoughts?

**Comment by gtdang** [comment]
Ah ok. So that would be more along Option 1? The GH Action would just call that function.

**Comment by younesStrittmatter** [comment]
Yes. I hope this way it shouldn't require many changes in the cookiecutter template itself.

**Comment by gtdang** [comment]
Ok I can get started on that next week.

**Comment by benwandrew** [comment]
i think the "All" option might indeed confusing to external contributors. so sounds good to me. i would love to be part of any meeting.

**Comment by gtdang** [comment]
Had a meeting on 5/22. 
* Discussed that having a separate function would be optimal instead of having more options in the cookiecutter prompt.
    - Will use the pytest framework of creating permutations in temp directories and copying the directories into a main directory
    - Readme will have jinja constructs stripped. Need to see if this will look readable or if further formatting is needed. 
* Younes will look into the best way to implement a GH action to push a full template to its own repository. Ideally this would run whenever there is a change to the cookiecutter template repo. 
* This work will be lower priority than the repo separation push because we have a MVP already.

**Comment by gtdang** [comment]
@benwandrew I think it's just a way for contributors to not be required to use cookiecutter and want a more traditional method of cloning from a repository. They'll clone a repository with everything and just delete and edit the things they don't want manually.

**Comment by younesStrittmatter** [comment]
Hi, I think this does exactly what we want: https://github.com/cpina/github-action-push-to-another-repository

**Comment by younesStrittmatter** [comment]
Here is a way to use it: https://stackoverflow.com/questions/64374179/how-to-push-to-another-repository-in-github-actions

**Comment by benwandrew** [comment]
ha, @younesStrittmatter i was actually looking at exactly that while we were talking yesterday. sounds good.
